//! Trap handling functionality
//!
//! For rCore on x86-64, there are two entry points:
//!
//! - the `syscall` entry, whose address is stored in the `LSTAR` MSR. It
//!   synthesizes an interrupt-like frame and forwards to [`trap_handler()`].
//! - the exception stubs, pointed to by the IDT. The CPU switches to the
//!   kernel stack (the `rsp0` field of the TSS) and pushes the interrupt
//!   frame, then each stub forwards to [`trap_handler()`].
//!
//! [`trap_handler()`] then calls different functionality based on what
//! exactly the exception was. For example, syscalls go to [`syscall()`].

// Boot-time CPU structures are installed once in [`init()`] and then never
// touched again, so `static mut` (via raw pointers) is fine here.
#![allow(static_mut_refs)]
// `trap.S` is written in GNU/AT&T syntax.
#![allow(bad_asm_style)]

mod context;
mod gdt;
mod idt;
mod msr;
mod paging;
mod tss;

use crate::batch::run_next_app;
use crate::syscall::syscall;
use context::TRAP_SYSCALL;
use core::arch::global_asm;
use gdt::Gdt;
use idt::InterruptDescriptorTable;
use lazy_static::*;
use log::*;
use tss::TaskStateSegment;

global_asm!(include_str!("trap.S"));

static mut TSS: TaskStateSegment = TaskStateSegment::new();

lazy_static! {
    static ref GDT: Gdt = Gdt::new(core::ptr::addr_of!(TSS) as u64);
    static ref IDT: InterruptDescriptorTable = {
        let mut idt = InterruptDescriptorTable::new();
        for i in 0..256 {
            idt.set_handler(i, unsafe { exception_stub_addrs[i] } as u64);
        }
        idt
    };
}

unsafe extern "C" {
    /// the addresses of the 256 exception stubs, generated by `trap.S`
    static exception_stub_addrs: [usize; 256];
    safe fn syscall_entry();
    safe fn trap_stack_top();
}

/// initialize the CPU (GDT, IDT, syscall MSRs) and take over the page tables
pub fn init() {
    // set the kernel stack used when an interrupt switches from ring 3 to ring 0
    unsafe {
        core::ptr::addr_of_mut!(TSS).write(TaskStateSegment::with_rsp0(
            linker_symbol_addr!(trap_stack_top) as u64,
        ));
    }
    GDT.load();
    IDT.load();
    msr::syscall_init(linker_symbol_addr!(syscall_entry) as u64);
    paging::init();
}

#[unsafe(no_mangle)]
/// handle an interrupt, exception, or system call from user space
pub fn trap_handler(cx: &mut TrapContext) -> &mut TrapContext {
    match cx.trap_num {
        TRAP_SYSCALL => {
            let ret = syscall(cx.rax, [cx.rdi, cx.rsi, cx.rdx]);
            cx.rax = ret as usize;
        }
        14 => {
            println!("[kernel] PageFault in application, kernel killed it.");
            run_next_app();
        }
        13 | 6 => {
            println!("[kernel] IllegalInstruction in application, kernel killed it.");
            run_next_app();
        }
        _ => {
            panic!(
                "Unsupported trap: vector = {}, error_code = {:#x}, RIP = {:#x}",
                cx.trap_num, cx.error_code, cx.rip
            );
        }
    }
    cx
}

#[unsafe(no_mangle)]
/// A trap that happened in kernel mode (i.e. a kernel bug): report and halt.
pub extern "C" fn kernel_exception_panic(vector: usize) -> ! {
    error!(
        "[kernel] Exception #{} occurred in kernel mode, kernel halted.",
        vector
    );
    crate::uart::shutdown(true)
}

pub use context::TrapContext;
