//! Trap handling functionality
//!
//! For rCore on x86-64, there are two entry points:
//!
//! - the `syscall` entry, whose address is stored in the `LSTAR` MSR. It
//!   synthesizes an interrupt-like frame and forwards to [`trap_handler()`].
//! - the exception stubs, pointed to by the IDT. The CPU switches to the
//!   current task's kernel stack (the `rsp0` field of the TSS) and pushes the
//!   interrupt frame, then each stub forwards to [`trap_handler()`].
//!
//! [`trap_handler()`] then calls different functionality based on what
//! exactly the exception was. For example, syscalls go to [`syscall()`], and
//! the APIC timer interrupt (vector 32) triggers task preemption.

// Boot-time CPU structures are installed once in [`init()`] and then never
// touched again, so `static mut` (via raw pointers) is fine here.
#![allow(static_mut_refs)]
// `trap.S` is written in GNU/AT&T syntax.
#![allow(bad_asm_style)]

mod context;
mod gdt;
pub mod idt;
pub(crate) mod msr;
pub mod tss;

use crate::cpu::current_per_cpu_mut;
use crate::syscall::syscall;
use crate::task::{
    SignalFlags, check_signals_error_of_current, current_add_signal, current_trap_cx,
    exit_current_and_run_next, handle_signals, suspend_current_and_run_next,
};
use crate::timer;
use context::TRAP_SYSCALL;
use core::arch::global_asm;
use idt::InterruptDescriptorTable;
use lazy_static::*;
use log::*;

pub use gdt::{Gdt, KERNEL_CS, KERNEL_DS, TSS_SELECTOR};
pub use tss::TaskStateSegment;

global_asm!(include_str!("trap.S"));

lazy_static! {
    /// the shared IDT (the handler addresses are identical on every core; each
    /// core `lidt`s it separately)
    static ref IDT: InterruptDescriptorTable = {
        let mut idt = InterruptDescriptorTable::new();
        for i in 0..256 {
            idt.set_handler(i, unsafe { exception_stub_addrs[i] } as u64);
        }
        idt
    };
}

unsafe extern "C" {
    /// the addresses of the 256 exception stubs, generated by `trap.S`
    static exception_stub_addrs: [usize; 256];
    safe fn syscall_entry();
    safe fn trap_stack_top();
}

/// The virtual address of the `syscall_entry` stub (for the `LSTAR` MSR).
pub fn syscall_entry_addr() -> u64 {
    linker_symbol_addr!(syscall_entry) as u64
}

/// The virtual address of the BSP's initial trap stack top.
pub fn bsp_trap_stack_top() -> u64 {
    linker_symbol_addr!(trap_stack_top) as u64
}

/// Load the shared IDT on the current processor.
pub fn load_shared_idt() {
    IDT.load();
}

/// Switch the kernel stack that the CPU uses for traps to `top`.
///
/// Both the `rsp0` field of this core's TSS (used for user-mode exceptions)
/// and its `current_stack_top` (used by `syscall_entry`) are updated. The task
/// manager calls this right before switching to another thread.
pub fn set_current_stack_top(top: u64) {
    let pc = current_per_cpu_mut();
    pc.current_stack_top = top as usize;
    pc.tss.set_rsp0(top);
}

/// The timer interrupt is enabled by the user RFLAGS IF bit (see
/// [`context::TrapContext::app_init_context`]) together with the APIC timer
/// setup done by [`crate::timer::init`]. The kernel itself deliberately keeps
/// IF cleared (interrupt gates and `SFMASK`) so that external interrupts only
/// happen in user mode, mirroring how RISC-V ch3 only enables `stimer` in
/// user mode. Nothing needs to be done here.
pub fn enable_timer_interrupt() {}

#[unsafe(no_mangle)]
/// handle an interrupt, exception, or system call from user space
pub fn trap_handler(cx: &mut TrapContext) -> &mut TrapContext {
    match cx.trap_num {
        TRAP_SYSCALL => {
            let ret = syscall(cx.rax, [cx.rdi, cx.rsi, cx.rdx]);
            // `cx` may have been replaced by `sys_exec` (it rebuilds the
            // TrapContext on the kernel stack), so fetch it again
            let cx = current_trap_cx();
            cx.rax = ret as usize;
        }
        32 => {
            // APIC timer interrupt (per-core local APIC)
            timer::timer_eoi();
            // only core 0 drives the global time base
            if crate::cpu::current_cpu_id() == 0 {
                timer::tick();
            }
            timer::set_next_trigger();
            // wake up any threads whose sleep deadline has expired
            timer::check_timer();
            suspend_current_and_run_next();
        }
        v @ 33..=255 => {
            // device IRQ while the CPU is in user mode: acknowledge it and
            // dispatch to the registered handler, then return to the
            // interrupted user code (no scheduling in IRQ context).
            dispatch_irq(v);
        }
        14 => {
            // page fault: CR2 holds the faulting linear address, error code
            // bit 1 distinguishes a store (write) from a load (read) fault
            let cr2: u64;
            unsafe {
                core::arch::asm!("mov rax, cr2", out("rax") cr2, options(nostack));
            }
            let access = if cx.error_code & 2 != 0 { "store" } else { "load" };
            // diagnostic: identify the faulting thread and its user RSP
            let (tid, rsp) = crate::task::current_task()
                .map(|t| {
                    let inner = t.inner_exclusive_access();
                    (
                        inner.res.as_ref().map(|r| r.tid).unwrap_or(usize::MAX),
                        inner.get_trap_cx().rsp,
                    )
                })
                .unwrap_or((usize::MAX, 0));
            println!(
                "[kernel] PageFault in application, {} addr = {:#x}, RIP = {:#x}, RSP = {:#x}, tid = {}, kernel killed it.",
                access, cr2, cx.rip, rsp, tid
            );
            current_add_signal(SignalFlags::SIGSEGV);
        }
        13 | 6 => {
            println!("[kernel] IllegalInstruction in application, kernel killed it.");
            current_add_signal(SignalFlags::SIGILL);
        }
        _ => {
            panic!(
                "Unsupported trap: vector = {}, error_code = {:#x}, RIP = {:#x}",
                cx.trap_num, cx.error_code, cx.rip
            );
        }
    }
    // handle the pending signals (including the ones just sent above)
    handle_signals();
    // the default action of an error signal is to kill the process
    if let Some((errno, msg)) = check_signals_error_of_current() {
        println!("[kernel] {}", msg);
        exit_current_and_run_next(errno);
    }
    let cx = current_trap_cx();
    cx
}

#[unsafe(no_mangle)]
/// A trap that happened in kernel mode (i.e. a kernel bug): report and halt.
pub extern "C" fn kernel_exception_panic(
    vector: usize,
    error_code: usize,
    fault_rip: usize,
    fault_cs: usize,
) -> ! {
    let cr2: u64;
    let cr3: u64;
    unsafe {
        core::arch::asm!("mov rax, cr2", out("rax") cr2, options(nostack));
        core::arch::asm!("mov rax, cr3", out("rax") cr3, options(nostack));
    }
    error!(
        "[kernel] Exception #{} (error_code = {:#x}) occurred in kernel mode, CR2 = {:#x}, CR3 = {:#x}, RIP = {:#x}, CS = {:#x}, kernel halted.",
        vector, error_code, cr2, cr3, fault_rip, fault_cs
    );
    crate::uart::shutdown(true)
}

#[unsafe(no_mangle)]
/// The APIC timer interrupt while running in kernel mode (an idle core's
/// `sti; hlt; cli` wakeup): EOI, advance the clock on core 0, and wake any
/// threads whose sleep deadline has expired. Returns via `iretq` back to the
/// idle loop.
pub extern "C" fn kernel_timer_eoi() {
    timer::timer_eoi();
    if crate::cpu::current_cpu_id() == 0 {
        timer::tick();
    }
    timer::check_timer();
}

/// Registered device IRQ handlers, indexed by IDT vector (`33..=255`).
///
/// Device IRQs (UART, virtio keyboard/mouse/gpu, ...) are delivered through
/// the local APIC as IDT vectors above the exception range. A driver registers
/// its handler here; `dispatch_irq` is invoked from both the user-mode
/// `trap_handler` and the kernel-mode IRQ path (`kernel_irq_dispatch`).
///
/// Handlers run in interrupt context and must **never** schedule or block:
/// they only drain device state and (at most) signal a condvar / enqueue a
/// task. They may take locks (ch9 `UPIntrFreeCell`), which mask interrupts on
/// the current core for the duration of the critical section.
static mut IRQ_HANDLERS: [Option<fn()>; 256] = [None; 256];

/// Register the handler for device IRQ `vector` (must be in `33..=255`).
///
/// Called once from `device_init` (boot, single-threaded).
pub fn register_irq(vector: usize, handler: fn()) {
    assert!(
        (33..=255).contains(&vector),
        "device IRQ vector {} out of range",
        vector
    );
    unsafe {
        IRQ_HANDLERS[vector] = Some(handler);
    }
    info!("irq: registered handler for vector {}", vector);
}

/// Acknowledge the interrupt (local APIC EOI) and run the registered handler
/// for `vector`. Called from both the user-mode and kernel-mode trap paths.
fn dispatch_irq(vector: usize) {
    timer::timer_eoi();
    let handler = unsafe { IRQ_HANDLERS[vector] };
    match handler {
        Some(h) => h(),
        None => panic!("Unhandled device IRQ vector {}", vector),
    }
}

#[unsafe(no_mangle)]
/// A device IRQ that arrived while running in kernel mode. This currently
/// happens only on an idle core's `sti; hlt` wakeup (the kernel otherwise
/// keeps IF cleared); it acknowledges the interrupt and dispatches to the
/// device handler, then returns via `iretq` to the interrupted kernel code.
pub extern "C" fn kernel_irq_dispatch(vector: usize) {
    dispatch_irq(vector);
}

pub use context::TrapContext;
