//! Trap handling functionality
//!
//! For rCore on x86-64, there are two entry points:
//!
//! - the `syscall` entry, whose address is stored in the `LSTAR` MSR. It
//!   synthesizes an interrupt-like frame and forwards to [`trap_handler()`].
//! - the exception stubs, pointed to by the IDT. The CPU switches to the
//!   current task's kernel stack (the `rsp0` field of the TSS) and pushes the
//!   interrupt frame, then each stub forwards to [`trap_handler()`].
//!
//! [`trap_handler()`] then calls different functionality based on what
//! exactly the exception was. For example, syscalls go to [`syscall()`], and
//! the APIC timer interrupt (vector 32) triggers task preemption.

// Boot-time CPU structures are installed once in [`init()`] and then never
// touched again, so `static mut` (via raw pointers) is fine here.
#![allow(static_mut_refs)]
// `trap.S` is written in GNU/AT&T syntax.
#![allow(bad_asm_style)]

mod context;
mod gdt;
mod idt;
pub(crate) mod msr;
mod tss;

use crate::syscall::syscall;
use crate::task::{
    SignalFlags, check_signals_error_of_current, current_add_signal, current_trap_cx,
    exit_current_and_run_next, handle_signals, suspend_current_and_run_next,
};
use crate::timer;
use context::TRAP_SYSCALL;
use core::arch::global_asm;
use gdt::Gdt;
use idt::InterruptDescriptorTable;
use lazy_static::*;
use log::*;
use tss::TaskStateSegment;

global_asm!(include_str!("trap.S"));

static mut TSS: TaskStateSegment = TaskStateSegment::new();

lazy_static! {
    static ref GDT: Gdt = Gdt::new(core::ptr::addr_of!(TSS) as u64);
    static ref IDT: InterruptDescriptorTable = {
        let mut idt = InterruptDescriptorTable::new();
        for i in 0..256 {
            idt.set_handler(i, unsafe { exception_stub_addrs[i] } as u64);
        }
        idt
    };
}

unsafe extern "C" {
    /// the addresses of the 256 exception stubs, generated by `trap.S`
    static exception_stub_addrs: [usize; 256];
    safe fn syscall_entry();
    safe fn trap_stack_top();
    static mut current_stack_top: usize;
}

/// initialize the CPU (GDT, IDT, syscall MSRs). Page tables are taken over
/// by [`crate::mm::init`].
pub fn init() {
    // set the kernel stack used when an interrupt switches from ring 3 to
    // ring 0. The task manager overwrites this with the per-task kernel stack
    // before the first task runs.
    set_current_stack_top(linker_symbol_addr!(trap_stack_top) as u64);
    GDT.load();
    IDT.load();
    msr::syscall_init(linker_symbol_addr!(syscall_entry) as u64);
}

/// Switch the kernel stack that the CPU uses for traps to `top`.
///
/// Both the `rsp0` field of the TSS (used for user-mode exceptions) and the
/// `current_stack_top` global (used by `syscall_entry`) are updated. The task
/// manager calls this right before switching to another task.
pub fn set_current_stack_top(top: u64) {
    unsafe {
        (*core::ptr::addr_of_mut!(TSS)).set_rsp0(top);
        current_stack_top = top as usize;
    }
}

/// The timer interrupt is enabled by the user RFLAGS IF bit (see
/// [`context::TrapContext::app_init_context`]) together with the APIC timer
/// setup done by [`crate::timer::init`]. The kernel itself deliberately keeps
/// IF cleared (interrupt gates and `SFMASK`) so that external interrupts only
/// happen in user mode, mirroring how RISC-V ch3 only enables `stimer` in
/// user mode. Nothing needs to be done here.
pub fn enable_timer_interrupt() {}

#[unsafe(no_mangle)]
/// handle an interrupt, exception, or system call from user space
pub fn trap_handler(cx: &mut TrapContext) -> &mut TrapContext {
    match cx.trap_num {
        TRAP_SYSCALL => {
            let ret = syscall(cx.rax, [cx.rdi, cx.rsi, cx.rdx]);
            // `cx` may have been replaced by `sys_exec` (it rebuilds the
            // TrapContext on the kernel stack), so fetch it again
            let cx = current_trap_cx();
            cx.rax = ret as usize;
        }
        32 => {
            // APIC timer interrupt
            timer::timer_eoi();
            timer::tick();
            timer::set_next_trigger();
            suspend_current_and_run_next();
        }
        14 => {
            // page fault: CR2 holds the faulting linear address, error code
            // bit 1 distinguishes a store (write) from a load (read) fault
            let cr2: u64;
            unsafe {
                core::arch::asm!("mov rax, cr2", out("rax") cr2, options(nostack));
            }
            let access = if cx.error_code & 2 != 0 { "store" } else { "load" };
            println!(
                "[kernel] PageFault in application, {} addr = {:#x}, RIP = {:#x}, kernel killed it.",
                access, cr2, cx.rip
            );
            current_add_signal(SignalFlags::SIGSEGV);
        }
        13 | 6 => {
            println!("[kernel] IllegalInstruction in application, kernel killed it.");
            current_add_signal(SignalFlags::SIGILL);
        }
        _ => {
            panic!(
                "Unsupported trap: vector = {}, error_code = {:#x}, RIP = {:#x}",
                cx.trap_num, cx.error_code, cx.rip
            );
        }
    }
    // handle the pending signals (including the ones just sent above)
    handle_signals();
    // the default action of an error signal is to kill the process
    if let Some((errno, msg)) = check_signals_error_of_current() {
        println!("[kernel] {}", msg);
        exit_current_and_run_next(errno);
    }
    let cx = current_trap_cx();
    cx
}

#[unsafe(no_mangle)]
/// A trap that happened in kernel mode (i.e. a kernel bug): report and halt.
pub extern "C" fn kernel_exception_panic(vector: usize, error_code: usize, fault_rip: usize) -> ! {
    let cr2: u64;
    unsafe {
        core::arch::asm!("mov rax, cr2", out("rax") cr2, options(nostack));
    }
    error!(
        "[kernel] Exception #{} (error_code = {:#x}) occurred in kernel mode, CR2 = {:#x}, RIP = {:#x}, kernel halted.",
        vector, error_code, cr2, fault_rip
    );
    crate::uart::shutdown(true)
}

pub use context::TrapContext;
